services:
  pi:
    container_name: pi
    build:
      context: .
      dockerfile: Dockerfile
    image: pi-coding-agent:latest
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./pi/extensions:/pi/extensions
      - ./pi/agent:/home/node/.pi/agent
      - ~/.ssh:/home/node/.ssh
      - ~/agent-registry:/home/node/agent-registry
      - ${HOST_WS:-./workspace}:/workspace
    working_dir: /workspace
